version: 0.0
os: linux
files:
  - source: gmt-server
    destination: /gmt/bin
  - source: gmt-api
    destination: /gmt/bin
  - source: app-spec/ci/gmt-server.service
    destination: /etc/systemd/system
  - source: app-spec/ci/gmt-api.service
    destination: /etc/systemd/system
  - source: app-spec/ci/.env
    destination: /gmt
hooks:
  BeforeInstall:
    - location: app-spec/ci/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: app-spec/ci/after_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: app-spec/ci/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: app-spec/ci/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: app-spec/ci/validate.sh
      timeout: 300
      runas: root