[package]
name = "gmt-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"

[dependencies.tracing-subscriber]
version = "0.3.18"
default-features = false
features = [ "fmt", "ansi", "chrono" ]