[package]
name = "gmt-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-server = { path = "../git-server" }
log = "0.4.21"
password-auth = "1.0.0"
ssh-server = { path = "../ssh-server" }
