name: Ci-Deploy

on:
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: eu-west-3

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: npm ci
        working-directory: gmt-web-app
      
      - name: Install cdk
        run : npm install -g aws-cdk

      - name: Build rust projects
        run: cargo build --release

      - name: Make sdk
        run: npm run make-sdk
        working-directory: gmt-web-app
      
      - name: Build front
        run: npm run build
        working-directory: gmt-web-app
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::446114629971:role/GithubActionRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install cdk dependencies
        run: npm install
        working-directory: gmt-cdk

      - name: Deploy
        run: cdk deploy GmtCdkStack-ci-${{ github.event.pull_request.number }} --require-approval never
        working-directory: gmt-cdk
        env:
          GH_PULL_ID: ${{ github.event.pull_request.number }}

      - name: Bundle back-end application
        run: |
          mkdir -p dist
          cp target/release/gmt-server dist/gmt-server
          cp target/release/gmt-api dist/gmt-api
          cp -r app-spec dist
          cp app-spec/appspec.yml dist
          zip -r app.zip dist

      - name: Upload application to S3
        run: aws s3 cp app.zip s3://gmt-pull-ci-artefacts-bucket-${{ github.event.pull_request.number }}/app.zip

      - name: Deploy application to CodeDeploy
        run: aws deploy create-deployment
          --application-name gmt-pull-${{ github.event.pull_request.number }}-api-application 
          --deployment-group-name gmt-pull-${{ github.event.pull_request.number }}-api-deployment-group
          --s3-location bucket=gmt-pull-ci-artefacts-bucket-${{ github.event.pull_request.number }},key=app.zip,bundleType=zip
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --description "Deploying app from PR ${{ github.event.pull_request.number }}"
