name: Ci-Deploy

on:
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: eu-west-3

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: gmt-web-app
      
      - name: Install cdk
        run : npm install -g aws-cdk

      - name: Build rust projects
        run: cargo build --release

      - name: Make sdk
        run: npm run make-sdk
        working-directory: gmt-web-app
      
      - name: Build front
        run: npm run build
        working-directory: gmt-web-app
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::446114629971:role/GithubActionRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install cdk dependencies
        run: npm install
        working-directory: gmt-cdk

      - name: Deploy
        run: cdk deploy GmtCdkStack-ci --require-approval never
        working-directory: gmt-cdk
        env:
          GH_PULL_ID: ${{ github.event.pull_request.number }}
