name: React

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gmt-web-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build api to generates openapi types
        run: cargo build
        working-directory: gmt-api

      - name: Make sdk
        run: npm run make-sdk

      - name: Check linting
        run: npm run lint

      - name: Format code
        run: npm run format:check

      - name: Run tests
        run: npm test