name: React

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin_user
          POSTGRES_DB: mentor_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    defaults:
      run:
        working-directory: gmt-web-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build api to generates openapi types
        run: cargo build
        working-directory: gmt-api

      - name: Make sdk
        run: npx openapi --input ../gmt-api/openapi/main_service.json --output ./src/gmt-api --postfixServices "" --name "main_service"

      - name: Check linting
        run: npm run lint

      - name: Format code
        run: npm run format:check

      - name: Run tests
        run: npm test